CREATE DATABASE SAOCAMILO;

USE SAOCAMILO;

CREATE TABLE EVENTOS(
	ID INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT UNIQUE,
    EVENTO VARCHAR(50) NOT NULL,
    DATAEVENTO DATE,
    PRIMARY KEY(ID)
);